# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T5R0Tv25TqSoA543o7shZujFQDP_1vSU
"""

import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

x_train, x_test = x_train / 255.0, x_test / 255.0

class_names = ["Samolot", "Samochód", "Ptaszek", "Kot", "Jelonek", "Pies",
               "Żaba", "Koń", "Statek", "Ciężarówka"]

plt.figure(figsize=(10, 10))
for i in range(9):
    plt.subplot(3, 3, i + 1)
    plt.imshow(x_train[i])
    plt.title(class_names[int(y_train[i])])
    plt.axis("off")
plt.show()

# model CNN
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),

    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),

    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),

    tf.keras.layers.Flatten(),

    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.summary()

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(x_train, y_train,
                    epochs=10,
                    validation_data=(x_test, y_test))

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Dokładność treningowa')
plt.plot(history.history['val_accuracy'], label='Dokładność walidacyjna')
plt.xlabel('Epoka')
plt.ylabel('Dokładność')
plt.legend()
plt.title('Dokładność modelu podczas treningu')
plt.grid(True)
plt.show()

test_loss, test_accuracy = model.evaluate(x_test, y_test)
print("Test accuracy:", test_accuracy)

predictions = model.predict(x_test)

plt.figure(figsize=(10, 10))
for i in range(9):
  plt.subplot(3, 3, i + 1)
  plt.imshow(x_test[i])
  plt.title(f"True: {class_names[int(y_test[i])]}," +
f"Predicted: {class_names[tf.argmax(predictions[i])]}")
  plt.axis("off")
plt.show()

"""Zadanie 1: Dodanie dodatkowych warstw konwolucyjnych"""

model_extra_conv = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(32, 32, 3)),

    tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),

    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),

    tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),

    tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

model_extra_conv.compile(optimizer='adam',
                         loss='sparse_categorical_crossentropy',
                         metrics=['accuracy'])

model_extra_conv.summary()

history_extra_conv = model_extra_conv.fit(x_train, y_train,
                                          epochs=10,
                                          validation_data=(x_test, y_test),
                                          verbose=1)

test_loss_extra, test_acc_extra = model_extra_conv.evaluate(x_test, y_test, verbose=0)

test_loss_extra, test_acc_extra = model_extra_conv.evaluate(x_test, y_test)
print(f"Model z dodatkowymi warstwami - Test accuracy: {test_acc_extra:.4f}")

"""Zadanie 2: Dropout"""

model_dropout = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(32, 32, 3)),

    tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Dropout(0.25),

    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Dropout(0.25),

    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(10, activation='softmax')
])

model_dropout.compile(optimizer='adam',
                     loss='sparse_categorical_crossentropy',
                     metrics=['accuracy'])

model_dropout.summary()

history_dropout = model_dropout.fit(x_train, y_train,
                                   epochs=10,
                                   validation_data=(x_test, y_test),
                                   verbose=1)

test_loss_dropout, test_acc_dropout = model_dropout.evaluate(x_test, y_test, verbose=0)

test_loss_dropout, test_acc_dropout = model_dropout.evaluate(x_test, y_test)
print(f"Model z Dropout - Test accuracy: {test_acc_dropout:.4f}")

"""Zadanie 3: Zmiana funkcji aktywacji"""

# Model z funkcją aktywacji tanh zamiast relu
model_tanh = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(32, 32, 3)),

    tf.keras.layers.Conv2D(32, (3, 3), activation='tanh'),
    tf.keras.layers.MaxPooling2D((2, 2)),

    tf.keras.layers.Conv2D(64, (3, 3), activation='tanh'),
    tf.keras.layers.MaxPooling2D((2, 2)),

    tf.keras.layers.Conv2D(64, (3, 3), activation='tanh'),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64, activation='tanh'),
    tf.keras.layers.Dense(10, activation='softmax')
])

model_tanh.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

model_tanh.summary()

print("Trening modelu z funkcją tanh...")
history_tanh = model_tanh.fit(x_train, y_train,
                              epochs=10,
                              validation_data=(x_test, y_test),
                              verbose=1)

test_loss_tanh, test_acc_tanh = model_tanh.evaluate(x_test, y_test, verbose=0)

test_loss_tanh, test_acc_tanh = model_tanh.evaluate(x_test, y_test)
print(f"Model z tanh - Test accuracy: {test_acc_tanh:.4f}")

import matplotlib.pyplot as plt

models_names = ['Bazowy', 'Dodatkowe\nwarstwy', 'Dropout', 'tanh']
accuracies = [0.6635, 0.6694, 0.1000, 0.5969]

plt.figure(figsize=(10, 6))
colors = ['blue', 'green', 'red', 'orange']
bars = plt.bar(models_names, accuracies, color=colors)

plt.ylabel('Dokładność', fontsize=12)
plt.title('Porównanie dokładności różnych modeli', fontsize=14)
plt.ylim([0, 0.8])
plt.grid(axis='y', alpha=0.3)

for bar, acc in zip(bars, accuracies):
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height + 0.01,
             f'{acc:.2%}',
             ha='center', va='bottom', fontsize=11, fontweight='bold')

plt.tight_layout()
plt.show()

"""Wyniki:

| Model | Dokładność |
|-------|-----------|
| Bazowy | 66.35% |
| Dodatkowe warstwy | 66.94% (najlepszy) |
| Dropout | 10.00% (najgorszy) |
| Tanh | 59.69% |

---

Wpływ modyfikacji na dokładność

Dodatkowe warstwy:
- Poprawiły wynik o 0.59%
- Więcej warstw = model lepiej rozpoznaje złożone obiekty
- Model był stabilny

Dropout:
- Całkowita katastrofa - model niczego się nie nauczył
- Wartości Dropout były zbyt wysokie
- Dropout źle zastosowany blokuje uczenie

Funkcja tanh:
- Pogorszyła wynik o 6.66%
- Tanh działa gorzej niż ReLU w sieciach CNN
- ReLU jest lepszym wyborem

---

Które modyfikacje miały największy wpływ?

- Pozytywny: Dodatkowe warstwy (+0.59%)
- Negatywny: Dropout (-56.35%)

---

Obserwacje

Co działa:
- Więcej warstw Conv poprawia wyniki
- ReLU jest lepsza niż tanh
- Proste modele często działają lepiej

Co nie działa:
- Zbyt wysoki Dropout
- Funkcja tanh w CNN
- Skomplikowane architektury nie zawsze pomagają

---

Podsumowanie

Najlepszy model miał dodatkowe warstwy (66.94%).

Wnioski:
- CNN potrzebują dobrej konfiguracji
- Sprawdzone rozwiązania (ReLU, więcej warstw) działają najlepiej
- Złe parametry mogą całkowicie zniszczyć model
- Dla małych obrazów prostsze sieci są wystarczające
"""

